spring:
  application:
    name: cards_qa

server:
  port: 8061

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true


eureka:
  instance:
    preferIpAddress: true
    fetchRegistry: true
    registryWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: "cards"
    description: "Test Cards qa"
    version: 1.0.0

logging:
  level:
    com:
      user:
        load:
          api2: DEBUG